### ISSUE TITLE
Is there a better way to paint multiple tilesets?

### ISSUE THREAD

**Issue by ThePinkos** [pablogila/TileMapDual_godot_node#1]
Do i need to have a node for each one of the tilesets (terrain)?

![image](https://github.com/user-attachments/assets/9e7ff29a-f311-472f-ae80-73c024b0294e)

Like this

![image](https://github.com/user-attachments/assets/d4c6964c-7927-405d-8cb6-1589f6bad73d)

**Comment by pablogila** [comment]
In principle yes. Although a cleaner approach may go like this. However, I am experimenting with multiple atlas_id right now, so that might change in the future.
![MultipleTilesets](https://github.com/user-attachments/assets/495828c9-77fb-43ca-9512-43e3f8dced7c)

**Comment by ThePinkos** [comment]
I'll let you know when I try it. I'll be home in a couple of hours.

**Comment by pablogila** [comment]
v2.4.0 now fully supports multiple atlases
