### ISSUE TITLE
Cursor Dual Script file atlas_id var is null on startup

### ISSUE THREAD

**Issue by Roqueasoto** [pablogila/TileMapDual_godot_node#3]
First of all thanks for this! 

Just one issue I ran into is that when you run the project and try to update the terrain, the game crashes because the atlas Id is null until you use one of the inputs to set it to a specific value. I fixed this by providing a default value of 0 in the cursor dual file, and after that it works as intended.

<img width="691" alt="Screenshot 2024-09-12 at 12 16 43 AM" src="https://github.com/user-attachments/assets/a139f963-e17b-42fd-a4c5-c74ead7c2c91">

The reason the fill_tile and erase_tile methods' default value is not used is because we do pass in a value for the atlas_id, its just null at first, and hence the crash.

**Comment by pablogila** [comment]
Good point! I will fix it later, thanks!
