### ISSUE TITLE
Have tile variations

### ISSUE THREAD

**Issue by shomykohai** [pablogila/TileMapDual_godot_node#6]
It would be amazing having support for variations of a tile.

For example, when dealing with an atlas of dirt and grass, having a variation of the grass tile with flowers or grass blades could be a possible scenario.

I tried using Godot built-in alternate tiles, but they don't seem to do what I want to achieve.

**Comment by pablogila** [comment]
You mean having randomised variations? That sounds interesting, although I have some doubts about the implementation. It may be possible to achieve that effect by having several atlases, but then how do you make sure that those tiles merge properly with each other? Could this be achieved with a different and easier method, such as adding random transparent tiles with your variations on top of the map...?

If you could please specify what you have in mind, maybe with an example, that would be awesome :D

**Comment by shomykohai** [comment]
Sure, here an example tileset of what i was thinking.
![tileset_jess](https://github.com/user-attachments/assets/64a39bb0-971a-4132-8284-a24a689a1a10)

Unfortunately the script won't allow me to place them on the world and instead just act like an empty tile when placing it.
But basically, the tiles on the bottom should act like an alternative for the full grass tile.

This is what i would like to achieve.
![image](https://github.com/user-attachments/assets/51a40afe-1f28-4a64-bfeb-27600a1043c9)


It would be also amazing if other tiles, like the corner ones, could have a variation.
Normally in Godot this could be achieved by using terrains and giving the tile the same pattern for similar tiles:
![image](https://github.com/user-attachments/assets/384f57ed-d63e-4b0e-8ff7-33cd57690d13)

**Comment by pablogila** [comment]
I see a couple of problems here. Since the double grid is displaced, your tile variations would have an offset of half a tile. Also, these tile variations would not appear near the edges. If we instead choose to keep the non-full or empty cells visible in the world grid, there is no easy way to round the edges. For this reason, only the full and empty tiles are used for drawing in the dual tileset. For now, it is much easier and simpler to just draw your tile variations on another regular TileMapLayer node placed on top. It would be even simpler if your tile variations had transparency: for example, if you just drew the flower with a transparent background. Since this alternative is so easy to achieve, I don't really see the point of complicating the code. If you have a different or simpler implementation in mind, please let me know.

**Comment by shomykohai** [comment]
> I see a couple of problems here. Since the double grid is displaced, your tile variations would have an offset of half a tile. Also, these tile variations would not appear near the edges. If we instead choose to keep the non-full or empty cells visible in the world grid, there is no easy way to round the edges. For this reason, only the full and empty tiles are used for drawing in the dual tileset. For now, it is much easier and simpler to just draw your tile variations on another regular TileMapLayer node placed on top. It would be even simpler if your tile variations had transparency: for example, if you just drew the flower with a transparent background. Since this alternative is so easy to achieve, I don't really see the point of complicating the code. If you have a different or simpler implementation in mind, please let me know.

It would be quite inconvenient having to make different atlas textures just to make a variation for one tile, especially making more tilemap layers.

One way I thought about making it is by having an export value where you can add variations by declaring the atlas coordinates for a variations and to which tile it corresponds.
I'll try making an implementation and see if it gets too complicated.

**Comment by pablogila** [comment]
Okay, let me know what you get!  :D

**Comment by shomykohai** [comment]
> Okay, let me know what you get!  :D

I tried making an implementation, and unfortunately it seems hard to make it both easy and in a single file without sacrificing functionality and readability of the code.

The main issues are:
* The multiple atlases to take into account when assigning variations (we'd need to know to which atlas an alternative tile is referred to)
* Godot does not allow to export custom classes with data nor resources if they come from the same file, thus I would have to export an array of dictionaries without typing, and this is not ideal.

If there were a way to surpass these obstacles, the path to get it working would be quite linear.
Unfortunately this little features is what is keeping me from switching from normal tilemaps to dual grid.

**Comment by pablogila** [comment]
Well, thanks for trying. Have you tried drawing your variations manually, with a regular TileMapLayer, with transparent backgrounds?

**Comment by shomykohai** [comment]
> Well, thanks for trying. Have you tried drawing your variations manually, with a regular TileMapLayer, with transparent backgrounds?

This works, but at the cost of having to make a new tilemap layer just to add variations. This makes it overwhelming when having to deal with multiple atlases each having variations.

Ideally, the approach of Godot default autotiling is much more scalable for multiple terrain types.
I understand though that dual-grid and terrains have substantial differences to be able to compare them.

Also i noticed how in my current setup with normal tilemaps, i have multiple "types" of tile in the same layer (Grass, Water, Sand and so on) named "Ground", thanks to autotiling "autoconnect" feature. I don't think the current implementation of the dual grid is able to distinguish the tiles, but this is probably another issue not on topic.

Anyway,

**Comment by pablogila** [comment]
Yeah, it's not an easy thing to do. I'm afraid it's a lot harder to implement than just using multiple layers or Godot's own system. So for now, unless someone comes up with a brilliant pull request that addresses this, using multiple layers will be the default solution for this plugin.
